fos_ck_editor:
    configs:
        default:
            toolbar: "default"
            uiColor: "#EDEEEF"
    toolbars:
        configs:
            default: ["@basicstyles", '-', "@paragraph" , '-', "@links", '-', "@items",'-',['Maximize'], '/' , '@aligment','-','@fontstyles' , '-' , ['Source']]
        items:
            basicstyles: [ "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-", "RemoveFormat" ]
            fontstyles: ['Styles', 'Format', 'FontSize', "-", 'TextColor', 'BGColor']
            paragraph:   [ "NumberedList", "BulletedList", "-", "Outdent", "Indent", "-", "Blockquote" ]
            links:       [ "Link", "Unlink" ]
            items: [ 'Image', 'CreateDiv', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'Iframe' ]
            aligment: [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'  ]