twig:
    paths: 
        "%kernel.root_dir%/../vendor/Essedi/EasyTranslation/src/Resources": Essedi
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@Essedi/Form/translation.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
