twig:
    paths: 
        "%kernel.root_dir%/../vendor/Essedi/EasyTranslation/src/Resources": EssediEasyTranslation
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@Essedi/Resources/translation.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
