twig:
    paths: 
        "%kernel.root_dir%/../vendor/essedi/translation/src/Resources/views": EssediEasyTranslation
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@EssediEasyTranslation/easy_admin/translation.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
